# To build latest GitHub app
MINUS_STD=gnu++20
DEPL_TARG=10.15

DCMTK_MAJOR=3
DCMTK_MINOR=7
DCMTK_BUILD=0
DCMTK_VERSION=$DCMTK_MAJOR.$DCMTK_MINOR.$DCMTK_BUILD
#DCMTK_OPTIONS="-D DCMTK_WITH_OPENSSL=ON -D DCMTK_WITH_ICONV=ON"
DCMTK_OPTIONS="-D DCMTK_WITH_OPENSSL=ON -D DCMTK_WITH_ICONV=ON -D WITH_OPENSSLINC=ON -D OPENSSL_VERSION_CHECK=ON"
DCMTK_CXX_FLAGS=FOR_MIELE_LXIV

#-------------------------------------------------------------------------------
ICONV_VERSION=1.18

#-------------------------------------------------------------------------------
#OPENSSL_VERSION=1.1.0j

OPENSSL_MAJOR=3
OPENSSL_MINOR=6
OPENSSL_REVISION=0

OPENSSL_VERSION=$OPENSSL_MAJOR.$OPENSSL_MINOR.${OPENSSL_REVISION}${OPENSSL_PATCH}

#-------------------------------------------------------------------------------

PNG_VERSION=1.6.51

TIFF_VERSION=4.7.1

#ZLIB_VERSION=1.3.1
ZLIB_VERSION=1.3.2

XML2_VERSION=2.15.1

#-------------------------------------------------------------------------------
VTK_MAJOR=9
VTK_MINOR=5
VTK_BUILD=2

VTK_VERSION=$VTK_MAJOR.$VTK_MINOR.$VTK_BUILD
VTK_OPTIONS="-D VTK_RENDERING_BACKEND:STRING=OpenGL2"
#VTK_TIFF 4.0.9
#VTK_JPEG 8d  15-Jan-2012

#-------------------------------------------------------------------------------
ITK_MAJOR=5
ITK_MINOR=4
ITK_BUILD=5
ITK_VERSION=$ITK_MAJOR.$ITK_MINOR.$ITK_BUILD

#-------------------------------------------------------------------------------

GLEW_VERSION=2.3.0
GLEW_OPTIONS="-D BUILD_UTILS=ON -D BUILD_FRAMEWORK=ON"

GLM_VERSION=1.0.2

#JASPER_VERSION=4.2.8
JASPER_VERSION=4.2.9

JPEG_VERSION=9f

OPENJPG_MAJOR=2
OPENJPG_MINOR=5
OPENJPG_BUILD=4
OPENJPG_TAR=v$OPENJPG_MAJOR.$OPENJPG_MINOR.$OPENJPG_BUILD
OPENJPG_VERSION=$OPENJPG_MAJOR.$OPENJPG_MINOR.$OPENJPG_BUILD

#-------------------------------------------------------------------------------

MING_VERSION=0_4_8

#-------------------------------------------------------------------------------
MIELE_VERSION=9.51.164
